-- MySQL Script generated by MySQL Workbench
-- 01/12/16 17:02:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema restaurant_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `restaurant_db` ;

-- -----------------------------------------------------
-- Table `restaurant_db`.`dining_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`dining_table` (
  `id` VARCHAR(45) NOT NULL,
  `number_of_seat` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`customer` (
  `id` VARCHAR(45) NOT NULL,
  `dining_table_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_dining_table1_idx` (`dining_table_id` ASC),
  CONSTRAINT `fk_customer_dining_table1`
    FOREIGN KEY (`dining_table_id`)
    REFERENCES `restaurant_db`.`dining_table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`call_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`call_message` (
  `id` VARCHAR(45) NOT NULL,
  `status` INT NULL,
  `called_times` INT NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_call_message_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_call_message_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `restaurant_db`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`order` (
  `id` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL,
  `spend` DOUBLE NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `restaurant_db`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`manager` (
  `id` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`menu` (
  `id` VARCHAR(45) NOT NULL,
  `manager_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_manager1_idx` (`manager_id` ASC),
  CONSTRAINT `fk_menu_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `restaurant_db`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`dish` (
  `id` VARCHAR(45) NOT NULL,
  `type` INT NULL,
  `name` VARCHAR(45) NULL,
  `spend` DOUBLE NULL,
  `waiting_time` DOUBLE NULL,
  `tag` INT NULL,
  `menu_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dish_menu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_dish_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `restaurant_db`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`order_has_dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`order_has_dish` (
  `order_id` VARCHAR(45) NOT NULL,
  `dish_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`, `dish_id`),
  INDEX `fk_order_has_dish_dish1_idx` (`dish_id` ASC),
  INDEX `fk_order_has_dish_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_dish_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `restaurant_db`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_dish_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `restaurant_db`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`set_meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`set_meal` (
  `id` VARCHAR(45) NOT NULL,
  `spend` VARCHAR(45) NULL,
  `menu_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_set_meal_menu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_set_meal_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `restaurant_db`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`order_has_set_meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`order_has_set_meal` (
  `order_id` VARCHAR(45) NOT NULL,
  `set_meal_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`, `set_meal_id`),
  INDEX `fk_order_has_set_meal_set_meal1_idx` (`set_meal_id` ASC),
  INDEX `fk_order_has_set_meal_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_set_meal_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `restaurant_db`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_set_meal_set_meal1`
    FOREIGN KEY (`set_meal_id`)
    REFERENCES `restaurant_db`.`set_meal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`set_meal_has_dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`set_meal_has_dish` (
  `set_meal_id` VARCHAR(45) NOT NULL,
  `dish_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`set_meal_id`, `dish_id`),
  INDEX `fk_set_meal_has_dish_dish1_idx` (`dish_id` ASC),
  INDEX `fk_set_meal_has_dish_set_meal1_idx` (`set_meal_id` ASC),
  CONSTRAINT `fk_set_meal_has_dish_set_meal1`
    FOREIGN KEY (`set_meal_id`)
    REFERENCES `restaurant_db`.`set_meal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_set_meal_has_dish_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `restaurant_db`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `restaurant_db`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`log` (
  `id` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `manager_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_log_manager1_idx` (`manager_id` ASC),
  CONSTRAINT `fk_log_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `restaurant_db`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
